/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface": "#fff8f6",
        "inverse-on-surface": "#ffede7",
        "ash-cream": "#EFEAE0",
        "surface-variant": "#f1dfd8",
        "on-tertiary-container": "#e5f9ff",
        "on-primary-container": "#fff2ee",
        "on-surface": "#231916",
        "inverse-primary": "#ffb599",
        "on-secondary-fixed": "#261906",
        "surface-dim": "#e9d6d0",
        "tertiary-fixed-dim": "#7ad3ea",
        "on-secondary": "#ffffff",
        "primary": "#933d16",
        "on-tertiary": "#ffffff",
        "outline-variant": "#dcc1b7",
        "on-tertiary-fixed": "#001f26",
        "secondary-container": "#f6dcbb",
        "on-secondary-fixed-variant": "#55442c",
        "terrace-green": "#6B7A4F",
        "outline": "#89726a",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#7d2d05",
        "primary-fixed-dim": "#ffb599",
        "on-primary": "#ffffff",
        "secondary": "#6e5b42",
        "surface-container-high": "#f7e4de",
        "on-primary-fixed": "#370e00",
        "tertiary": "#006071",
        "secondary-fixed-dim": "#dcc3a4",
        "primary-fixed": "#ffdbce",
        "background": "#fff8f6",
        "on-surface-variant": "#56423b",
        "lava-danger": "#8C2F1B",
        "surface-container-highest": "#f1dfd8",
        "surface-container": "#fdeae4",
        "volcanic-ash": "#3A3733",
        "inverse-surface": "#392e2a",
        "error": "#ba1a1a",
        "surface-container-low": "#fff1ec",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#b3542c",
        "tertiary-container": "#007b90",
        "on-error": "#ffffff",
        "surface-bright": "#fff8f6",
        "tertiary-fixed": "#acedff",
        "surface-tint": "#9c431c",
        "on-background": "#231916",
        "on-secondary-container": "#735f46",
        "secondary-fixed": "#f9debe",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#004e5c"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "gutter": "1rem",
        "stack-md": "1rem",
        "stack-lg": "2rem",
        "margin-desktop": "3rem",
        "stack-sm": "0.5rem",
        "margin-mobile": "1.5rem"
      },
      "fontFamily": {
        "display-lg-mobile": ["Fraunces", "Literata", "serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "data-tabular": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Fraunces", "Literata", "serif"],
        "display-lg": ["Fraunces", "Literata", "serif"],
        "headline-md-mobile": ["Fraunces", "Literata", "serif"]
      },
      "fontSize": {
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "data-tabular": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-md-mobile": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "fontWeight": "700" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
