# Generated by Django 6.1.1 on 2026-09-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_id', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0.0)),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestData',
            fields=[
                ('harvest_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('planting_id', models.CharField(max_length=50)),
                ('date_harvest', models.DateField(blank=True, null=True)),
                ('commodity', models.CharField(max_length=100)),
                ('area_harvested_ha', models.FloatField(default=0.0)),
                ('production_ton', models.FloatField(default=0.0)),
                ('yield_ton_ha', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PlantingData',
            fields=[
                ('planting_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('farm_id', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('commodity', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100, null=True)),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('area_planted_ha', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('commodity', models.CharField(max_length=100)),
                ('price_rp_per_kg', models.FloatField(default=0.0)),
            ],
        ),
    ]
