# Generated by Django 6.1.1 on 2026-09-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_costdata_harvestdata_plantingdata_pricedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GISData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('ndvi', models.DecimalField(decimal_places=3, max_digits=5)),
                ('land_cover', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['farm_id'],
            },
        ),
        migrations.CreateModel(
            name='PestDiseaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('commodity', models.CharField(max_length=50)),
                ('pest_disease', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rainfall_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temperature_c', models.DecimalField(decimal_places=2, max_digits=6)),
                ('humidity_percent', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
